### ISSUE TITLE
Scrolling does not work when set to "on"

### ISSUE THREAD

**Issue by o0shojo0o** [o0shojo0o/node-red-contrib-pixelit#3]
Hi, I updated to 0.3.7. Brightness and sleep works fine again, scrolling works wenn set to "auto". Thanks for fixing it!
Scrolling does not work when set to "on", it displays a static text then. I am fine with the auto setting :)

btw. the latest version does not show up in the node-red palette, I updated with npm install.

_Originally posted by @hamster65 in https://github.com/o0shojo0o/node-red-contrib-pixelit/issues/2#issuecomment-814636922_

**Comment by o0shojo0o** [comment]
Fixt in v0.3.8 :)

**Comment by hamster65** [comment]
Nice, thanks! Scrolling with "on" works. 
I found another bug with automatic scrolling: When I send "WINDBÖEN", the last 2 colomns of the last character do not fit (normal text size), so it should auto-scroll, but it doesn't. Sometimes, it displays a static text, but sometimes it shows just random pixels. When it fades to the next screen, the text is readable again during the fade.

**Comment by o0shojo0o** [comment]
> When I send "WINDBÖEN", the last 2 colomns of the last character do not fit

Yes, unfortunately the Pixelit can't calculate that cleanly, I don't have a solution for that, because the letters are not all the same width.

> Sometimes, it displays a static text, but sometimes it shows just random pixels. When it fades to the next screen, the text is readable again during the fade.

This behavior can not be produced by these nodes, this indicates malfunctions in the power supply or wiring.

**Comment by hamster65** [comment]
Issues with wiring or power supply should give flickering and "colorfull" pixels. But here it only happens with scrolling set to auto, brightness does not influence it and all pixels are in the exact color of the text.

I noticed I had position x=7, y=1 and center=on set in the text node. I set this to zero and disabled and the problem was gone. Then I set it back to reproduce it and it is still gone... Odd.
